#-------------------------------
# General Site Settings

menu:
- title: Blog
  url: blog
#- title: Open Source
#  url: open-source

social:
- url:  https://github.com/steffenpedersen
  icon: github
- url: https://www.linkedin.com/in/mrsteffenpedersen/
  icon: linkedin
- url:  https://dev.to/steffenpedersen
  icon: dev
- url:  https://twitter.com/mrsteffenp
  icon: twitter
